server:
  port: 80

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.sprint.mission.discodeit: info
    org.hibernate.SQL: info

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2

    kafka:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      consumer:
        group-id: discodeit-group
        auto-offset-reset: earliest
      producer:
        acks: all

management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: false

jwt:
  max-active-count: 5